const products = [
    { id: 1, name: "Bracelet Acier", category: "bracelets", price: 13.76, rating: 5, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088608/1000004836_hdc33u.png", buyers: [], desc: "Bracelet en acier inoxydable de haute qualit&eacute;. Design &eacute;l&eacute;gant et intemporel, finition soign&eacute;e. Taille r&eacute;glable (20-22 cm). Id&eacute;al pour un look raffin&eacute; au quotidien. Livraison rapide au Maroc." },
    { id: 2, name: "Bracelet Acier Design", category: "bracelets", price: 13.76, rating: 5, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088625/1000004832_yubwqc.png", gallery: ["https://res.cloudinary.com/dx5d98buj/image/upload/v1783088625/1000004832_yubwqc.png", "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088670/1000004832_ksfrle.png"], buyers: [], desc: "Bracelet en acier inoxydable au design moderne et &eacute;l&eacute;gant. Finition soign&eacute;e, confortable &agrave; porter. Taille r&eacute;glable (20-22 cm). Parfait pour un look sophistiqu&eacute; au quotidien." },
    { id: 3, name: "Bracelet Acier Classique", category: "bracelets", price: 13.76, rating: 5, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088463/1000004829_kwovzu.png", gallery: ["https://res.cloudinary.com/dx5d98buj/image/upload/v1783088463/1000004829_kwovzu.png", "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088479/1000004830_o6olo4.png"], buyers: [], desc: "Bracelet en acier inoxydable classique et &eacute;l&eacute;gant. Finition de haute qualit&eacute;, design intemporel. Taille r&eacute;glable (20-22 cm). Id&eacute;al pour toutes les occasions." },
    { id: 4, name: "Bracelet Acier Luxe", category: "bracelets", price: 13.76, rating: 5, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088695/1000004835_v4bvtl.png", buyers: [], desc: "Bracelet en acier inoxydable de luxe au design raffin&eacute;. Finition premium, &eacute;clat brillant. Taille r&eacute;glable (20-22 cm). Un choix d'exception pour homme &eacute;l&eacute;gant." },
    { id: 5, name: "Bracelet Acier Premium", category: "bracelets", price: 13.76, rating: 4, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783088649/1000004833_aeknnw.png", buyers: [], desc: "Bracelet en acier inoxydable premium au design &eacute;pur&eacute;. Maille fine et &eacute;l&eacute;gante, fermeture s&eacute;curis&eacute;e. Taille r&eacute;glable (20-22 cm). Le choix parfait pour un homme distingu&eacute;." },
    { id: 6, name: "Bracelet Acier Noir", category: "bracelets", price: 13.76, rating: 4, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783379278/1000004873_scy1pm.png", buyers: [], desc: "Bracelet en acier inoxydable noir au design &eacute;l&eacute;gant et moderne. Finition soign&eacute;e, look &eacute;pur&eacute;. Taille r&eacute;glable (20-22 cm). Id&eacute;al pour un style contemporain." },
    { id: 7, name: "Collier Acier", category: "colliers", price: 13.76, rating: 4, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783379244/1000004868_wvsegx.jpg", buyers: [], desc: "Collier en acier inoxydable au design &eacute;l&eacute;gant. Finition soign&eacute;e, cha&icirc;ne solide et confortable (50 cm). Parfait pour homme moderne. Livraison rapide au Maroc." },
    { id: 8, name: "Bracelet Cuir Noir", category: "bracelets", price: 16.53, rating: 4, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783379263/1000003310_u3ga98.jpg", buyers: [], desc: "Bracelet en cuir noir au design &eacute;l&eacute;gant. Boucle en acier inoxydable, finition soign&eacute;e, look moderne. Taille r&eacute;glable. Parfait pour homme." },
    { id: 9, name: "Le bracelet rouge aux 7 nœuds de la Kabbale", category: "bracelets", price: 7.85, rating: 5, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1783419943/t%C3%A9l%C3%A9charger_16_pkhxhh.jpg", buyers: [], desc: "Bracelet rouge Kabbale aux 7 n&oelig;uds. Fil rouge traditionnel porte-bonheur en coton, &eacute;l&eacute;gant et protecteur. Taille unique. 85 DHS." },
];
if (typeof module !== "undefined") module.exports = { products };
