const products = [
    { id: 18, name: "Bracelet Acier Dor&eacute; Fins", category: "bracelets", price: 18.37, rating: 3, image: "https://res.cloudinary.com/dx5d98buj/image/upload/v1782902266/images_BRA_ARG_2_r6vj5s.jpg", buyers: ["Nora S."], desc: "Bracelet en acier inoxydable dor&eacute; aux maillons fins et d&eacute;licats. Placage or de haute qualit&eacute;, finition brillante, fermoir s&eacute;curis&eacute;. L&eacute;ger et &eacute;l&eacute;gant, il apporte une touche raffin&eacute;e &agrave; toutes vos tenues, du quotidien aux occasions sp&eacute;ciales." },
    { id: 20, name: "Bracelet Acier Noir Matt", category: "bracelets", price: 18.37, rating: 4, image: "IMAGE/bracelet-1.png", buyers: ["Yassine E.", "Nawal R."], desc: "Bracelet en acier inoxydable noir mat. Design moderne et discret, id&eacute;al pour un look urbain." },
    { id: 21, name: "Bracelet Chaîne Dor&eacute;e", category: "bracelets", price: 18.37, rating: 5, image: "IMAGE/bracelet-2.png", buyers: ["Khalid T.", "Meryem A.", "Soufiane B."], desc: "Bracelet cha&icirc;ne en acier inoxydable dor&eacute;. Maillons fins et &eacute;l&eacute;gants, fermoir s&eacute;curis&eacute;." },
    { id: 22, name: "Bracelet Perles Acier", category: "bracelets", price: 18.37, rating: 4, image: "IMAGE/bracelet-3.png", buyers: ["Hicham Z.", "Fatima L."], desc: "Bracelet en acier inoxydable avec perles argent&eacute;es. Style raffin&eacute; et original pour homme." },
    { id: 23, name: "Bracelet Acier", category: "bracelets", price: 18.37, rating: 4, image: "IMAGE/bracelet-4.png", buyers: ["Amine R.", "Sara L."], desc: "Bracelet en acier inoxydable argent&eacute; au design intemporel. Maillons classiques polis, fermoir d&eacute;ployant grav&eacute;, finition anti-allergique. Un incontournable pour homme &eacute;l&eacute;gant qui traverse les saisons sans perdre de son &eacute;clat." },
    { id: 25, name: "Robuste", category: "bracelets", price: 21.15, rating: 4, image: "IMAGE/CABL3.png", gallery: ["IMAGE/CABL3.png", "IMAGE/CABL2.png"], buyers: ["Karim H.", "Nadia T."], desc: "Bracelet robuste en acier inoxydable de haute résistance. Maillons renforcés, finition brossée anti-rayures, fermoir sécurisé à double verrouillage. Conçu pour les hommes actifs qui exigent durabilité et style au quotidien." },
    { id: 26, name: "Valentino Fil", category: "bracelets", price: 10.62, rating: 4, image: "IMAGE/NOIR.jfif", gallery: ["IMAGE/NOIR.jfif", "IMAGE/VERT.jfif", "IMAGE/NOIR.jfif"], colors: { "Noir": "IMAGE/NOIR.jfif", "Vert": "IMAGE/VERT.jfif" }, buyers: ["Ali M.", "Sara K."], desc: "Bracelet Valentino VLOGO Signature en coton de haute qualit&eacute;. Tressage artisanal, fermeture coulissante adjustable. Un accessoire embl&eacute;matique alliant le raffinement italien &agrave; un confort absolu pour un usage quotidien." },
    { id: 27, name: "Bracelet Acier Argent&eacute; Classique", category: "bracelets", price: 12.83, rating: 4, image: "IMAGE/bracelet-acier-argente.jpg", buyers: ["Omar B.", "Imane L."], desc: "Bracelet en acier inoxydable argent&eacute; de haute qualit&eacute;. Maillons polis miroir, fermoir d&eacute;ployant grav&eacute;, finition anti-allergique. Un style intemporel pour homme &eacute;l&eacute;gant &agrave; 139 DHS." },
    { id: 28, name: "Bracelet Acier Dor&eacute; Luxe", category: "bracelets", price: 12.83, rating: 5, image: "IMAGE/bracelet-acier-dore-luxe.png", buyers: ["Mehdi T.", "Laila R."], desc: "Bracelet en acier inoxydable plaqu&eacute; or. &Eacute;clat dor&eacute; premium, maillons fins et sophistiqu&eacute;s, fermoir s&eacute;curit&eacute;. Id&eacute;al pour un look raffin&eacute; &agrave; seulement 139 DHS." },
    { id: 29, name: "Bracelet Acier Noir Matt", category: "bracelets", price: 12.83, rating: 4, image: "IMAGE/bracelet-acier-argente.jpg", buyers: ["Younes K.", "Salma A."], desc: "Bracelet en acier inoxydable noir mat. Design contemporain, finition bross&eacute;e anti-rayures, fermoir ajustable. Le choix parfait pour un style moderne et discret &agrave; 139 DHS." },
    { id: 30, name: "Ceinture Herm&egrave;s Paris", category: "accessoires", price: 32.22, rating: 5, image: "IMAGE/ceinture-hermes.jpg", buyers: ["Karim O."], desc: "Ceinture Herm&egrave;s Paris boucle r&eacute;versible avec bracelet en cuir 32mm. &Eacute;l&eacute;gance intemporelle, fabrication artisanale de luxe. Un accessoire incontournable pour homme distingu&eacute; &agrave; 349 DHS." },
    { id: 31, name: "Ceinture Cuir Vintage", category: "accessoires", price: 32.22, rating: 4, image: "IMAGE/ceinture-cuir.jpg", buyers: ["Hicham Z."], desc: "Ceinture en cuir vintage avec boucle argent&eacute;e. Style classique et raffin&eacute;, fabrication haut de gamme. Id&eacute;ale pour compl&eacute;ter une tenue &eacute;l&eacute;gante au quotidien &agrave; 349 DHS." },
    { id: 32, name: "Portefeuille Homme Cuir", category: "accessoires", price: 13.76, rating: 4, image: "IMAGE/portefeuille-cuir.jpg", buyers: ["Amine T."], desc: "Portefeuille homme en cuir de vachette de haute qualit&eacute;. Design classique &eacute;l&eacute;gant, multiples compartiments, finition soign&eacute;e. Un accessoire essentiel pour homme raffin&eacute; &agrave; 149 DHS." },
    { id: 33, name: "Porte-Carte Homme", category: "accessoires", price: 16.53, rating: 4, image: "IMAGE/porte-carte-noir.jpg", gallery: ["IMAGE/porte-carte-noir.jpg", "IMAGE/porte-carte-sulpice.jpg", "IMAGE/porte-carte-goyard.jpg", "IMAGE/porte-carte-sulpice2.jpg", "IMAGE/porte-carte-sulpice3.jpg"], colors: { "Noir": "IMAGE/porte-carte-noir.jpg", "Marron": "IMAGE/porte-carte-sulpice.jpg", "Goyardine": "IMAGE/porte-carte-goyard.jpg", "Tabac": "IMAGE/porte-carte-sulpice2.jpg", "Bleu": "IMAGE/porte-carte-sulpice3.jpg" }, buyers: ["Sami K."], desc: "Porte-carte homme en cuir de luxe. Design raffin&eacute; et compact, multiples emplacements. Un accessoire pratique et &eacute;l&eacute;gant au quotidien &agrave; 179 DHS." }
];
